<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>

<script>
    'use strict';
    (function(hyva) {
        const formValidationRules = {
            required(value, options, field, context) {
                field.element.setAttribute('required', '');
                field.element.checkValidity();
                if (field.element.validity.valueMissing) {
                    return '<?= $escaper->escapeJs(__('This field is required.')) ?>';
                }
                return true;
            },
            maxlength(value, options, field, context) {
                field.element.setAttribute('maxlength', options);
                field.element.checkValidity();
                if (field.element.validity.tooLong) {
                    return hyva.strf('<?= $escaper->escapeJs(__('Please enter no more than "%0" characters.')) ?>', options);
                }
                return true;
            },
            minlength(value, options, field, context) {
                field.element.setAttribute('minlength', options);
                field.element.checkValidity();
                if (field.element.validity.tooShort) {
                    return hyva.strf('<?= $escaper->escapeJs(__('Please enter at least "%0" characters.')) ?>', options);
                }
                return true;
            },
            max(value, options, field, context) {
                field.element.setAttribute('max', options);
                field.element.checkValidity();
                if (field.element.validity.rangeOverflow) {
                    return hyva.strf('<?= $escaper->escapeJs(__('Please enter a value less than or equal to "%0".')) ?>', options);
                }
                return true;
            },
            min(value, options, field, context) {
                field.element.setAttribute('min', options);
                field.element.checkValidity();
                if (field.element.validity.rangeUnderflow) {
                    return hyva.strf('<?= $escaper->escapeJs(__('Please enter a value greater than or equal to "%0".')) ?>', options);
                }
                return true;
            },
            step(value, options, field, context) {
                field.element.setAttribute('step', options);
                field.element.checkValidity();
                if (field.element.validity.stepMismatch) {
                    const val = Number(options);
                    return hyva.strf('<?= $escaper->escapeJs(__('Please enter a valid value. The two nearest valid values are "%0" and "%1".')) ?>', Math.floor(val), Math.ceil(val));
                }
                return true;
            },
            email(value, options, field, context) {
                <?php // The same email validation regex is also used in the Magento backend ?>
                const rule = /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i;
                if (!rule.test(value)) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid email address.')) ?>';
                }
                return true;
            },
            password(value, options, field, context) {
                const rule = /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/;
                if (!rule.test(value)) {
                    return '<?= $escaper->escapeJs(__('Please provide at least one upper case, one lower case, one digit and one special character (#?!@$%^&*-)')) ?>';
                }
                return true;
            },
            equalTo(value, options, field, context) {
                const dependencyField = context.fields[options].element;
                const dependencyFieldName = dependencyField.label || dependencyField.name;
                if (value !== dependencyField.value) {
                    return hyva.strf('<?= $escaper->escapeJs(__('This field value must be the same as "%0".')) ?>', dependencyFieldName);
                }
                return true;
            }
        };

        function addFormValidationRule(name, validator) {
            formValidationRules[name] = validator;
        }

        function formValidation(formElement, options) {
            // disable browser default validation
            if (formElement.tagName === 'FORM') {
                formElement.setAttribute('novalidate', '');
            } else {
                console.error('formValidation can be initialized only on FORM element', formElement);
                return;
            }

            options = Object.assign({
                fieldWrapperClassName: 'field',
                fieldWrapperAdditionalClasses: '',
                messagesWrapperClassName: 'messages',
                validClassName: 'field--success',
                invalidClassName: 'field--error'
            }, options || {});

            return {
                state: {
                    valid: false,
                    touched: false
                },
                fields: {},
                idSeq: 0,
                idPrefix: formElement.id || 'vld-msg',
                elementWillValidate(element) {
                    return element.willValidate && element.tagName !== 'BUTTON' && element.disabled === false && !(element.tagName === 'INPUT' && element.type === 'submit')
                },
                setupFields(elements) {
                    Array.from(elements).forEach((element) => {
                        if (this.elementWillValidate(element)) {
                            this.setupField(element);
                        }
                    });
                },
                setupField(element) {
                    if (this.elementWillValidate(element)) {
                        this.fields[element.name] = {
                            element,
                            rules: this.getRules(element),
                            state: {
                                valid: null,
                                touched: null,
                                rules: {}
                            }
                        }
                    } else {
                        console.error('Element will not validate', element);
                    }
                },
                onSubmit(event) {
                    if (event.target.tagName === 'FORM') {
                        this.state.touched = true;
                        this.validate().catch((invalid) => {
                            if (invalid.length > 0) {
                                invalid[0].focus();
                            }
                            event.preventDefault();
                        });
                    }
                },
                onChange(event) {
                    if (!Object.keys(this.fields).length) {
                        this.setupFields(formElement.elements);
                    }
                    if (!Object.keys(this.fields).includes(event.target.name)) {
                        this.setupField(event.target);
                    }
                    const field = this.fields[event.target.name];

                    field.state.touched = true;
                    this.validateField(field);
                },
                validate() {
                    if (!Object.keys(this.fields).length || !Object.keys(this.fields).length !== formElement.elements.length) {
                        this.setupFields(formElement.elements);
                    }
                    return new Promise((resolve, reject) => {
                        if (formElement.elements) {
                            this.validateFields();
                            const invalidFields = Object.values(this.fields).filter(field => !field.state.valid);
                            this.state.valid = invalidFields.length === 0;
                            if (this.state.valid) {
                                resolve();
                            } else {
                                reject(invalidFields.map(field => field.element));
                            }
                        }
                    });
                },
                validateFields() {
                    Object.values(this.fields).forEach(field => this.validateField(field));
                },
                validateField(field) {
                    const value = field.element.type === 'checkbox' ? field.element.checked : field.element.value;
                    const rules = field.rules;
                    if (rules) {
                        Object.keys(rules).forEach(rule => {
                            if (formValidationRules[rule]) {
                                field.state.rules[rule] = this.runValidateFn(rule, rules[rule], value, field);
                            } <?php if ($viewModels->require(StoreConfig::class)->isDeveloperMode()): ?>
                            else {
                                console.error(hyva.strf('Unknown validation rule "%0" found on field', rule), field.element);
                            }
                            <?php endif; ?>
                        });
                        field.state.valid = !Object.values(field.state.rules).some(this.isInvalidRule);
                    } else {
                        field.state.valid = true;
                    }

                    this.setFieldStates(field);
                },
                runValidateFn(rule, options, value, field) {
                    return formValidationRules[rule](value, options, field, this);
                },
                getRules(element) {
                    let rules = {};
                    const BROWSER_ATTRS = ['min', 'max', 'required', 'minlength', 'maxlength', 'step'];
                    const DEFAULT_TYPES = ['email', 'password'];
                    BROWSER_ATTRS.forEach(attrName => {
                        if (element.hasAttribute(attrName)) {
                            rules[attrName] = element.getAttribute(attrName);
                        }
                    })
                    DEFAULT_TYPES.forEach(typeName => {
                        if (element.type === typeName) {
                            rules[typeName] = true;
                        }
                    })

                    const validation = element.dataset.validate;
                    if (validation) {
                        try {
                            rules = Object.assign(rules, JSON.parse(validation));
                        } catch (error) {
                            console.error('Validator error. Cannot parse data-validate attribute of element:\n', element);
                        }
                    }

                    return rules;
                },
                isInvalidRule(ruleState) {
                    return typeof ruleState === 'string' || !ruleState;
                },
                getMessagesByField(field) {
                    const messages = [];
                    const invalidRules = Object.keys(field.state.rules).filter(rule => this.isInvalidRule(field.state.rules[rule]));

                    field.rules && Object.keys(field.rules).forEach((rule) => {
                        if (invalidRules.includes(rule)) {
                            const customMessage = field.element.getAttribute('data-msg-' + rule);
                            const message = customMessage ? customMessage : field.state.rules[rule];
                            const ruleOptions = JSON.parse(JSON.stringify(field.rules[rule]));

                            if (typeof message !== 'string') {
                                messages.push(hyva.strf('Validation rule "%0" failed.', rule));
                            } else if (Array.isArray(ruleOptions)) {
                                ruleOptions.unshift(message);
                                messages.push(hyva.strf.apply(null, ruleOptions));
                            } else {
                                messages.push(hyva.strf(message, ruleOptions));
                            }
                        }
                    });
                    return messages;
                },
                setFieldStates(field) {

                    function createFieldParent(el) {
                        if (el.parentElement) {
                            const wrapper = document.createElement('div');
                            wrapper.classList.add(options.fieldWrapperClassName);
                            wrapper.classList.add('generated-wrapper');
                            el.parentElement.insertBefore(wrapper, el);
                            wrapper.appendChild(el);
                            return wrapper;
                        }
                    }

                    const parentClass = `.${options.fieldWrapperClassName}`;
                    const parent = field.element.closest(parentClass) || createFieldParent(field.element);
                    if (parent) {
                        parent.classList.toggle(options.validClassName, field.state.valid);
                        parent.classList.toggle(options.invalidClassName, !field.state.valid);
                        this.createMessage(field, parent)
                    } <?php if ($viewModels->require(StoreConfig::class)->isDeveloperMode()): ?>
                    else {
                        console.error(`Cannot find parent element ${parentClass} of ${field.element.name}`, field.element);
                    }
                    <?php endif; ?>

                    if (field.state.valid) {
                        field.element.removeAttribute('aria-invalid');
                    } else {
                        field.element.setAttribute('aria-invalid', 'true');
                        if (! document.activeElement) {
                            field.element.focus();
                        }
                    }
                },
                createMessage(field, container) {
                    const msg = container.querySelector(`.${options.messagesWrapperClassName}`);
                    if (msg) {
                        field.element.removeAttribute('aria-errormessage');
                        msg.remove();
                    }

                    if (!field.state.valid) {
                        const messages = this.getMessagesByField(field);
                        const list = document.createElement('ul');
                        list.id = this.generateId();
                        list.classList.add(options.messagesWrapperClassName);
                        messages.forEach((message) => {
                            const li = document.createElement('li');
                            li.innerText = message;
                            list.appendChild(li);
                        });
                        field.element.insertAdjacentHTML('afterend', list.outerHTML);
                        field.element.setAttribute('aria-errormessage', list.id);
                    }
                },
                setField(name, value) {
                    this.fields[name].element.value = value;
                    this.fields[name].state.touched = true;
                    this.fields[name].element.dispatchEvent((new Event('input')));
                    this.validateField(this.fields[name]);
                },
                generateId() {
                    let id;
                    do {
                        id = `${this.idPrefix}-${++this.idSeq}`;
                    } while (document.getElementById(id));
                    return id;
                }
            }
        }

        hyva.formValidation = formValidation;
        hyva.formValidation.rules = formValidationRules;
        hyva.formValidation.addRule = addFormValidationRule;
    }(window.hyva = window.hyva || {}));
</script>
