<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<script type="module"
        src="<?= $block->escapeUrl($block->getViewFileUrl('Hyva_Theme::js/alpine-2.3.5.min.js')) ?>"
        defer
        crossorigin
></script>
