<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
?>
<script defer>
    'use strict';
    function dispatchMessages(messages, hideAfter) {
        var messagesEvent = new CustomEvent("messages-loaded", {
            detail: {
                messages: messages,
                hideAfter: hideAfter
            }
        });
        window.dispatchEvent(messagesEvent);
    }
    {
        var defaultConfig = {
            expires: null,
            path: '/',
            domain: null,
            secure: false,
            lifetime: null
        }

        function initFormKey() {
            var inputSelector = 'input[name="form_key"]';
            var allowedCharacters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
            var length = 16;

            function generateRandomString() {
                var formKey = '';
                var charactersLength = allowedCharacters.length;
                for (var i = 0; i < length; i++) {
                    formKey += allowedCharacters[Math.round(Math.random() * (charactersLength - 1))]
                }
                return formKey;
            }

            var formKey = getCookie('form_key');

            if (!formKey) {
                formKey = generateRandomString();
                setCookie('form_key', formKey);
            }
            Array.from(document.querySelectorAll(inputSelector)).map(function (input) {
                input.value = formKey
            });

        }

        function initMessages() {
            try {
                var messages = getCookie('mage-messages');
                messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];
                window.mageMessages = messages;
            } catch (error) {
                console.warn('Error parsing Cookie Messages:', error);
                return;
            }

            dispatchMessages(messages);

            <?php
            /**
             * In \Magento\Theme\Controller\Result\MessagePlugin::setCookie
             * the cookie-domain is not set. Therefore, we need to skip it
             * here as well.
             */
            ?>
            // empty `mage-messages` cookie
            const skipSetDomain = true;
            setCookie('mage-messages','', -1, skipSetDomain);
        }

        function getCookie(name) {
            var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
            return v ? v[2] : null;
        }

        function setCookie(name, value, days, skipSetDomain) {
            var expires,
                path,
                domain,
                secure;

            var cookieConfig = window.COOKIE_CONFIG || {};

            if (days) {
                expires = lifetimeToExpires({lifetime: 24 * 60 * 60 * days, expires: null}, defaultConfig);
            } else {
                expires = lifetimeToExpires(window.COOKIE_CONFIG, defaultConfig) || defaultConfig.expires;
            }
            path = cookieConfig.path || defaultConfig.path;
            domain = !skipSetDomain && (cookieConfig.domain || defaultConfig.domain);
            secure = cookieConfig.secure || defaultConfig.secure;

            document.cookie = name + "=" + encodeURIComponent(value) +
                (expires ? '; expires=' + expires.toGMTString() :  '') +
                (path ? '; path=' + path : '') +
                (domain ? '; domain=' + domain : '') +
                (secure ? '; secure' : '');
        }

        function lifetimeToExpires(options, defaults) {

            var lifetime = options.lifetime || defaults.lifetime;

            if (lifetime) {
                var date = new Date;
                date.setTime(date.getTime() + lifetime * 1000);
                return date;
            }

            return null;
        }

        window.addEventListener('load', function () {
            initFormKey();
            initMessages();
        })
    }
</script>
