<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    'use strict';
    function dispatchMessages(messages, hideAfter) {
        var messagesEvent = new CustomEvent("messages-loaded", {
            detail: {
                messages: messages,
                hideAfter: hideAfter
            }
        });
        window.dispatchEvent(messagesEvent);
    }

<?php
    /**
     * The `hyva` JS namespace is being set by Hyva_Theme/src/view/frontend/templates/page/js/hyva.phtml
     * and should be included through Hyva_Theme/src/view/frontend/layout/default_hyva.xml
     */
?>
    if (typeof hyva === 'undefined' || (!hyva.getBrowserStorage || !hyva.getCookie || !hyva.setCookie)) {
        console.warn("Hyvä helpers are not loaded yet. Make sure they are included before this script");
    }

    {
        var defaultConfig = {
            expires: null,
            path: '/',
            domain: null,
            secure: false,
            lifetime: null
        }

        function initFormKey() {
            var inputSelector = 'input[name="form_key"]';
            var allowedCharacters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
            var length = 16;

            function generateRandomString() {
                var formKey = '';
                var charactersLength = allowedCharacters.length;
                for (var i = 0; i < length; i++) {
                    formKey += allowedCharacters[Math.round(Math.random() * (charactersLength - 1))]
                }
                return formKey;
            }

            var formKey = hyva.getCookie('form_key');

            if (!formKey) {
                formKey = generateRandomString();
                hyva.setCookie('form_key', formKey);
            }
            Array.from(document.querySelectorAll(inputSelector)).map(function (input) {
                input.value = formKey
            });

        }

        function initMessages() {
            try {
                var messages = hyva.getCookie('mage-messages');
                messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];
                window.mageMessages = messages;
            } catch (error) {
                console.warn('Error parsing Cookie Messages:', error);
                return;
            }

            dispatchMessages(messages);

            <?php
            /**
             * In \Magento\Theme\Controller\Result\MessagePlugin::setCookie
             * the cookie-domain is not set. Therefore, we need to skip it
             * here as well.
             */
            ?>
            // empty `mage-messages` cookie
            const skipSetDomain = true;
            hyva.setCookie('mage-messages','', -1, skipSetDomain);
        }

        window.addEventListener('load', function () {
            initFormKey();
            initMessages();
        })
    }
</script>
