<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<script>
    'use strict';
    {
        var private_content_key = 'mage-cache-storage';
        var private_content_expire_key = 'mage-cache-timeout';
        var private_content_version_key = 'private_content_version';
        var mage_cache_session_id_key = 'mage-cache-sessid';

        var ttl = 3600;

<?php
        /**
         * The `hyva` JS namespace is being set by Hyva_Theme/src/view/frontend/templates/page/js/hyva.phtml
         * and should be included through Hyva_Theme/src/view/frontend/layout/default_hyva.xml
         */
?>
        if (typeof hyva === 'undefined' || (!hyva.getBrowserStorage || !hyva.getCookie || !hyva.setCookie)) {
            console.warn("Hyvä helpers are not loaded yet. Make sure they are included before this script");
        }

        function loadSectionData () {
            var browserStorage = hyva.getBrowserStorage();
            if (!browserStorage) {
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: "warning",
                        text: "<?= $escaper->escapeHtml(__('Please enable LocalStorage in your browser.')) ?>"
                    }]
                );
                return;
            }
            try {
                var isInvalid = false;

<?php
                /**
                 * The `mage-cache-sessid` cookie is being unset from backend to
                 * indicate that sectionData is invalidated and needs to be reloaded
                 * in the frontend. So we mark it as invalid, and then re-set the
                 * `mage-cache-sessid` cookie
                 */
?>
                if (!hyva.getCookie(mage_cache_session_id_key)) {
                    isInvalid = true;
                    const skipSetDomain = true;
                    const days = false;
                    hyva.setCookie(mage_cache_session_id_key, true, days, skipSetDomain)
                }

                var cookieVersion = hyva.getCookie(private_content_version_key);
                var storageVersion = browserStorage.getItem(private_content_version_key);

                if (cookieVersion && !storageVersion || cookieVersion !== storageVersion) {
                    isInvalid = true;
                }

                var privateContentExpires = browserStorage.getItem(private_content_expire_key);
                if (privateContentExpires && new Date(privateContentExpires) < new Date()) {
                    browserStorage.removeItem(private_content_key);
                }

                if (isInvalid) {
                    fetchPrivateContent([]);
                    browserStorage.setItem(private_content_version_key, cookieVersion);
                } else if (cookieVersion && storageVersion && cookieVersion === storageVersion) {
                    var privateContent = JSON.parse(browserStorage.getItem(private_content_key));
                    if (
                        privateContent &&
                        privateContentExpires &&
                        privateContent.cart &&
                        privateContent.customer
                    ) {
                        dispatchPrivateContent(privateContent);
                    } else {
                        fetchPrivateContent([]);
                    }
                } else {
                    dispatchPrivateContent({});
                }

            } catch (error) {
                console.warn('Error retrieving Private Content:', error);
            }
        }

        window.addEventListener('load', loadSectionData);
        window.addEventListener('reload-customer-section-data', loadSectionData);

        function dispatchPrivateContent(data) {
            var privateContentEvent = new CustomEvent("private-content-loaded", {
                detail: {
                    data: data
                }
            });
            window.dispatchEvent(privateContentEvent);
        }

<?php
        /**
         * We use 'X-Requested-With': 'XMLHttpRequest' to prevent Magento from clearing the customer session
         * in \Magento\PageCache\Model\DepersonalizeChecker::checkIfDepersonalize
         * Otherwise, \Magento\Tax\Plugin\Checkout\CustomerData\Cart::afterGetSectionData can't add tax to
         * cart items.
         */
?>
        function fetchPrivateContent(sections) {
            fetch('<?= $escaper->escapeUrl(
                $block->getBaseUrl()
            ) ?>/customer/section/load/?sections=' + encodeURIComponent(
                sections.join(',')
            ), {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
                .then(function (response) {
                    return response.json()
                })
                .then(
                    function (data) {
                        if (data) {
                            dispatchPrivateContent(data);

                            // don't persist messages, they've been dispatched already
                            if ( data.messages && data.messages.messages ) {
                                data.messages.messages = []
                            }
                            try {
                                var browserStorage = hyva.getBrowserStorage();
                                browserStorage.setItem(private_content_key, JSON.stringify(data));
                                browserStorage.setItem(
                                    private_content_expire_key,
                                    new Date(Date.now() + (ttl * 1000)).toISOString()
                                );
                            } catch (error) {
                                console.warn("Couldn't store privateContent", error);
                            }
                        }
                    }
                );
        }
    }
</script>
