<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @experimental
 *
 * This template may change in backward incompatible ways without notice, since the speculation-rules browser API it depends on is experimental, too.
 */

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>
<script type="speculationrules">
{
    "prerender": [{
        "source": "document",
        "where": {
            "and": [
                { "href_matches": "/*.html" },
                { "not": {"selector_matches": ".do-not-prerender"}}
            ]
        },
        "eagerness": "moderate"
    }]
}
</script>
