<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\View\Element\Template;

/** @var HyvaCsp $hyvaCsp */
/** @var Template $block */

/**
 * @experimental
 *
 * This template may change in backward incompatible ways without notice,
 * since the speculation-rules browser API it depends on is experimental, too.
 *
 * @link https://developer.chrome.com/docs/web-platform/prerender-pages
 * @link https://caniuse.com/mdn-html_elements_script_type_speculationrules
 */

?>
<script type="speculationrules">
{
    "tag": "hyva",
    "prerender": [{
        "source": "document",
        "where": {
            "and": [
                { "href_matches": "/*" },
                { "not": {
                    "href_matches": [
                        "/customer/*",
                        "*/customer/*",
                        "/search/*",
                        "*/search/*",
                        "/sales/*",
                        "*/sales/*",
                        "/wishlist/*",
                        "*/wishlist/*",
                        "/checkout/*",
                        "*/checkout/*",
                        "/paypal/*",
                        "*/paypal/*",
                        "*.pdf"
                    ]
                }},
                { "not": { "selector_matches": ".do-not-prerender" } },
                { "not": { "selector_matches": "[download]" } },
                { "not": { "selector_matches": "[rel~=nofollow]" } }

            ]
        },
        "eagerness": "moderate"
    }]
}
</script>
<?php $hyvaCsp->registerInlineScript() ?>
