<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

// Dispatch event for external scripts to listen for/load after the first user interaction initiated.
?>
<script>
    (events => {
        const dispatchUserInteractionEvent = () => {
            events.forEach(type => window.removeEventListener(type, dispatchUserInteractionEvent))
            window.dispatchEvent(new Event('user.interaction.init'));
        };
        events.forEach(type => window.addEventListener(type, dispatchUserInteractionEvent, {once: true}))
    })(['touchstart', 'mouseover', 'wheel', 'scroll', 'keydown'])
</script>
