<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<script>
    // Dispatch event for external scripts to listen for/load after the first user interaction initiated.
    const userInteractionInitEvent = new CustomEvent('user.interaction.init');

    const dispatchUserInteractionEvent = () => {
        window.dispatchEvent(userInteractionInitEvent);
        console.debug('\'user.interaction.init\' event dispatched.');
        removeListeners();
    };

    const removeListeners = () => {
        window.removeEventListener('touchstart', dispatchUserInteractionEvent);
        window.removeEventListener('mouseover', dispatchUserInteractionEvent);
        window.removeEventListener('wheel', dispatchUserInteractionEvent);
        window.removeEventListener('scroll', dispatchUserInteractionEvent);
        window.removeEventListener('keydown', dispatchUserInteractionEvent);
    };

    window.addEventListener('touchstart', dispatchUserInteractionEvent, {once: true});
    window.addEventListener('mouseover', dispatchUserInteractionEvent, {once: true});
    window.addEventListener('wheel', dispatchUserInteractionEvent, {once: true});
    window.addEventListener('scroll', dispatchUserInteractionEvent, {once: true});
    window.addEventListener('keydown', dispatchUserInteractionEvent, {once: true});
</script>
