<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/**
 * This is the default modal confirmation dialog template
 * @see \Hyva\Theme\Model\Modal\ConfirmationBuilderInterface
 */

?>
<?php if ($block->hasData('title')): ?>
    <p id="clearShoppingCartModal" class="text-xl">
        <strong><?= $escaper->escapeHtml($block->getData('title')) ?></strong>
    </p>
<?php endif; ?>

<?php if ($block->hasData('details')): ?>
    <div>
        <?= /** @noEscape */ $block->getData('details') ?>
    </div>
<?php endif; ?>

<div class="actions-toolbar">
    <button type="button" class="btn btn-primary" @click="ok"><?= $escaper->escapeHtml(__('OK')) ?></button>
    <button type="button" class="btn" @click="cancel"><?= $escaper->escapeHtml(__('Cancel')) ?></button>
</div>
