<?php declare(strict_types=1);
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\Model\Modal\ModalInterface $modal */

/**
 * This is the default modal container template
 * @see \Hyva\Theme\Model\Modal\ModalBuilderInterface
 */

?>
<div <?= $modal->isInitiallyHidden() ? 'x-cloak' : '' ?> x-spread="overlay('<?= $escaper->escapeHtmlAttr($modal->getDialogRefName()) ?>')" class="<?= $escaper->escapeHtmlAttr($modal->getOverlayClasses()) ?>">
    <div x-ref="<?= $escaper->escapeHtmlAttr($modal->getDialogRefName()) ?>" role="dialog"
         <?php if ($modal->isOverlayDisabled()): ?>x-no-overlay<?php endif; ?>
         <?php if ($modal->getAriaLabel()): ?>
             aria-label="<?= $escaper->escapeHtmlAttr($modal->getAriaLabel()) ?>"
         <?php endif; ?>
         <?php if ($modal->getAriaLabelledby()): ?>
             aria-labelledby="<?= $escaper->escapeHtmlAttr($modal->getAriaLabelledby()) ?>"
         <?php endif; ?>
         class="<?= $modal->getDialogClasses() ?>">
        <?= $modal->getContentHtml() ?>
    </div>
</div>
