<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\DeployMode;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var HyvaCsp $hyvaCsp */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var DeployMode $deployMode */
$deployMode = $viewModels->require(DeployMode::class);
?>
<script>
    (function () {
        const initAlpine = window.deferLoadingAlpine || ((callback) => callback());
        window.deferLoadingAlpine = (callback) => {
            const origInitializeComponent = Alpine.initializeComponent;
            Alpine.initializeComponent = function (el) {
                if (! el.closest('[x-ignore]')) {
                    origInitializeComponent.call(this, el);
                }
            };
            initAlpine(callback);
        };
    })();
    <?php if ($deployMode->isDeveloperMode()): ?>
    //# sourceURL=alpine-ignore.js
    <?php endif; ?>
</script>
<?php $hyvaCsp->registerInlineScript() ?>
