<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\ThemeLibrariesConfig;
use Magento\Framework\View\Element\Template;

$themeLibrary = $viewModels->require(ThemeLibrariesConfig::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$block->setData('defer_idle_timeout', $storeConfig->getStoreConfig('hyva_theme_general/alpine_defer/defer_idle_timeout'));

$version = $themeLibrary->getVersionIdFor('defer-plugin')
    ?: $themeLibrary->getVersionIdFor('alpine')
    ?: '2';

$deferred = $block->getData('deferred_components') ?? [];

if ($deferredComponentsConfig = $storeConfig->getStoreConfig('hyva_theme_general/alpine_defer/deferred_components')) {
    foreach (json_decode($deferredComponentsConfig, true) ?: [] as $tuple) {
        $deferred[$tuple['selector']] = $tuple['defer_until'];
    }
}


?>
<?php if ($deferred): ?>
<script>
    for (const [selector, deferUntil] of Object.entries(<?= /** @noEscape */ json_encode($deferred) ?>)) {
        document.querySelectorAll(selector).forEach(el => el.setAttribute('x-defer', `${deferUntil}`));
    }
</script>
<?php endif ?>
<?= /** @noEscape */ $block->fetchView($block->getTemplateFile("Hyva_Theme::page/js/plugins/v{$version}/defer.phtml")) ?>
