<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */
?>
<script>
    (function () {
        "use strict";

        var DIRECTIVE = "intersect";
        var X_ATTR_RE = /^x-([a-z-]*)\b/i;

        function parseHtmlAttribute(_ref) {
            var name = _ref.name,
                value = _ref.value;

            const typeMatch = name.match(X_ATTR_RE);
            const valueMatch = name.match(/:([a-zA-Z0-9\-:]+)/);
            const modifiers = name.match(/\.[^.\]]+(?=[^\]]*$)/g) || [];

            return {
                type: typeMatch ? typeMatch[1] : null,
                value: valueMatch ? valueMatch[1] : null,
                modifiers: modifiers.map((i) => i.replace(".", "")),
                expression: value,
            };
        }

        function getXDirectives(el) {
            return Array.from(el.attributes)
                .filter(function (attr) {
                    return X_ATTR_RE.test(attr.name);
                })
                .map(parseHtmlAttribute);
        }

        if (window.Alpine) {
            console.error("Intersect plugin must be included before AlpineJs, x-intersect will not work.");
        }

        const getThreshhold = (modifiers) => {
            if (modifiers.includes("full")) return 0.8;
            if (modifiers.includes("half")) return 0.5;

            return 0;
        };

        var AlpineIntersectionDirective = {
            start: function start() {
                Alpine.onBeforeComponentInitialized(function (component) {
                    var legacyResolveBoundAttributes = component.resolveBoundAttributes;

                    component.resolveBoundAttributes = function (el, initialUpdate, extraVars) {
                        if (initialUpdate === void 0) {
                            initialUpdate = false;
                        }

                        if (initialUpdate) {
                            var attrs = getXDirectives(el);
                            attrs.forEach(function (_ref) {
                                let type = _ref.type,
                                    expression = _ref.expression,
                                    value = _ref.value,
                                    modifiers = _ref.modifiers;

                                if (type === DIRECTIVE) {
                                    let options = {
                                        threshold: getThreshhold(modifiers),
                                    };

                                    if ("IntersectionObserver" in window) {
                                        let observer = new IntersectionObserver((elements) => {
                                            elements.forEach((element) => {
                                                if (
                                                    (!element.isIntersecting && value === "enter") ||
                                                    (element.isIntersecting && value === "leave") ||
                                                    (!element.isIntersecting && !value)
                                                )
                                                    return;

                                                component.evaluateReturnExpression(el, expression, extraVars);

                                                modifiers.includes("once") && observer.disconnect();
                                            });
                                        }, options);

                                        observer.observe(el);
                                    } else {
                                        component.evaluateReturnExpression(el, expression, extraVars);
                                    }
                                }
                            });
                        }
                        return legacyResolveBoundAttributes.bind(component)(el, initialUpdate, extraVars);
                    };
                });
            },
        };

        const initAlpine = window.deferLoadingAlpine || ((callback) => callback());
        window.deferLoadingAlpine = (callback) => {
            AlpineIntersectionDirective.start();
            initAlpine(callback);
        };
    })();
</script>
