<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ThemeLibrariesConfig;
use Magento\Framework\View\Element\Template;

$themeLibrary = $viewModels->require(ThemeLibrariesConfig::class);

$version = $themeLibrary->getVersionIdFor('intersect-plugin')
    ?: $themeLibrary->getVersionIdFor('alpine')
    ?: '2';

$templateIdentifier = 'Hyva_Theme::page/js/plugins/v%s/intersect.phtml';
$template = $block->getTemplateFile(sprintf($templateIdentifier, $version));
if (! $template && substr($version, -4) === '-csp') {
    $template = $block->getTemplateFile(sprintf($templateIdentifier, substr($version, 0, -4)));
}

?>
<?= /** @noEscape */ $block->fetchView($template) ?>
