<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\PageJsDependencyRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var PageJsDependencyRegistry $jsDependencies */
$jsDependencies = $viewModels->require(PageJsDependencyRegistry::class);

// This $block is also used in \Hyva\Theme\Observer\RegisterPageJsDependencies::applyBlockOutputPatternJsDependencyRules

echo $jsDependencies->getJsDependenciesHtml();
